### ISSUE TITLE
Missing files in annotation.zip

### ISSUE THREAD

**Issue by cyh-0** [hxixixh/mix-and-localize#2]
Hi Xixi,

I think there are several mask files missing in the annotation.zip file for the VGGSound Instruments dataset. Could please update these missing masks please, thanks in advance.

Here are the missing files index
Drop index 0207
Drop index 0251
Drop index 0216
Drop index 0371
Drop index 0401
Drop index 0253
Drop index 0456
Drop index 0301
Drop index 0315
Drop index 8
Drop index 25
Drop index 41
Drop index 42
Drop index 47
Drop index 58
Drop index 61
Drop index 67
Drop index 71
Drop index 77
Drop index 88
Drop index 97
Drop index 104
Drop index 122
Drop index 128
Drop index 153
Drop index 163
Drop index 168
Drop index 171
Drop index 177
Drop index 178
Drop index 202
Drop index 203
Drop index 210
Drop index 232
Drop index 235
Drop index 236
Drop index 241
Drop index 264
Drop index 315
Drop index 324
Drop index 327
Drop index 329
Drop index 351
Drop index 356
Drop index 364
Drop index 376
Drop index 395
Drop index 408
Drop index 413
Drop index 432
Drop index 438
Drop index 441
Drop index 442
Drop index 448
Drop index 474

**Comment by hxixixh** [comment]
Hello @cyh-0, thanks for bringing this to our attention. We apologize for the confusion regarding the testing data. There are 500 samples in the testing data set, but only 446 of them are used for evaluation. The annotations for the remaining samples were not included because the mask quality was not sufficient. We will make sure to update the repository and dataset as soon as possible to reflect this information.

**Comment by cyh-0** [comment]
Thanks for the update!
