### ISSUE TITLE
Inconsistent Evaluation Metrics?

### ISSUE THREAD

**Issue by Franklin905** [hxixixh/mix-and-localize#8]
Hi,
Thank you for releasing the code!
I found out that the evaluation metrics in the code (line 233 in train.py) is accuracy but the metrics in the paper are AP, AUC, CAP, PIAP, etc.
So why is the metrics in the code different from the metrics in the paper? Did I misunderstand something?

**Comment by IFICL** [comment]
Hi, 

Since our method is self-supervised, we don't have any labels about the mask and bounding box annotations for calculating the metrics such as AP, AUC, CAP, PIAP during the training or validation. In this way, we monitor the accuracy of our training objectives to choose the best-performing model. We don't public the evaluation code in our repo.
